-- :WorktreeProfile <lang>
-- Drops a starter .envrc into the current cwd. Templates are intentionally
-- minimal — the user is expected to edit (project name, ports, ...) and run
-- `direnv allow` afterwards.

local templates = {}

templates.common_header = [[
# Generated by :WorktreeProfile. Edit, then run `direnv allow`.
# Requires direnv: https://direnv.net/

WT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null | tr '/' '_' || basename "$PWD")
WT_HASH=$(printf '%s' "$WT_BRANCH" | cksum | cut -d' ' -f1)
]]

templates.rails = templates.common_header .. [[
# Per-worktree DB so migrations don't trample each other.
# Run `bin/rails db:create db:migrate` (or `bin/setup`) once per new worktree.
export DATABASE_URL="postgres://localhost/myapp_${WT_BRANCH}"

# Deterministic dev-server port from branch name.
export PORT=$((3000 + WT_HASH % 1000))

# Tip: share gem path across worktrees once globally:
#   bundle config set --global path "$HOME/.bundle"
]]

templates.node = templates.common_header .. [[
# Vite / Next.js dev port — unique per worktree.
export PORT=$((3000 + WT_HASH % 1000))

# Next.js: avoid `.next/` collisions when running multiple worktrees concurrently.
# export NEXT_BUILD_DIR=".next-${WT_BRANCH}"

# Tip: share pnpm store once globally:
#   pnpm config set store-dir "$HOME/.pnpm-store"
]]

templates.go = templates.common_header .. [[
# HTTP port if your app reads $PORT.
export PORT=$((8000 + WT_HASH % 1000))

# Go module/build caches are global by default — no per-worktree action needed.
]]

local function write_envrc(content, force)
	local target = vim.fn.getcwd() .. "/.envrc"
	if vim.loop.fs_stat(target) and not force then
		vim.ui.input({ prompt = ".envrc already exists. Overwrite? (y/N): " }, function(ans)
			if ans and (ans:lower() == "y" or ans:lower() == "yes") then
				write_envrc(content, true)
			end
		end)
		return
	end

	local f, err = io.open(target, "w")
	if not f then
		vim.api.nvim_err_writeln("Failed to write " .. target .. ": " .. (err or "?"))
		return
	end
	f:write(content)
	f:close()

	print("Wrote " .. target)
	print("Next: edit project-specific values, then run `direnv allow`.")
end

vim.api.nvim_create_user_command("WorktreeProfile", function(opts)
	local lang = opts.args
	local body = templates[lang]
	if not body then
		vim.api.nvim_err_writeln("Unknown profile '" .. lang .. "'. Available: rails, node, go")
		return
	end
	write_envrc(body, false)
end, {
	nargs = 1,
	complete = function()
		return { "rails", "node", "go" }
	end,
	desc = "Drop a starter .envrc for the given language profile (rails/node/go)",
})
